### ISSUE TITLE
Application crashes with backtrace

### ISSUE THREAD

**Issue by jahknem** [RoPieee/roon-on-wine#12]
After installing the application using the script and then starting the application using ./start_my_roon_instance.sh the application crashes showing the wine window: "Programm Error: The rogramm Roon.exe encountered a serious problem and needs to close. We are sorry for the inconvenience." Under Details I can find the following backtrace:
[backtrace.txt](https://github.com/RoPieee/roon-on-wine/files/5372885/backtrace.txt)

OS: Linux pop-os 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux
CPU: i5 4590
RAM: 16 GB

Not really sure how to proceed..

EDIT: Spelling

**Comment by spockfish** [comment]
Wine still remains a 'best attempt effort'. So any problems with the Roon app itself is not something I can fix.
