### ISSUE TITLE
"your screen resolution is too small to run roon"

### ISSUE THREAD

**Issue by AtomicStick** [RoPieee/roon-on-wine#15]
Worked previously, but with the latest update to Roon 1.8 whenever I try to launch via start_my_roon_instance.sh I get the message that "Your screen resolution is too small to run Roon. Please try to run maximized or fullscreen." Maximized and fullscreen are links, and clicking them does in fact make the window maximized or fullscreen, but the message stays and no Roon. The screen is of course the same as it ever was, and is plenty big enough to run Roon. I have deleted the my_roon_instance directory and reinstalled the whole project from github, but to no avail.

**Comment by AtomicStick** [comment]
Rebooting everything seems to have corrected this, though still not sure what the issue was.

**Comment by jtmcn** [comment]
@AtomicStick were you able to resolve this issue? I'm running into the same thing. (Although reboot doesn't help)

**Comment by AtomicStick** [comment]
Yes and no. If I launch from Gnome and not the CLI it works fine. If I try to start it with start_my_roon_instance.sh I still get the error message. Didn't dig deeper to figure out why, as I just have it pinned to my favorites in the dock anyway.

**Comment by jtmcn** [comment]
Thanks. It does launch from the icon for me as well. Weird.
Unfortunately the UI looks pretty bad. The colors are off and the text is too small/jagged. It's frustrating that Roon doesn't seem to care about Linux desktop users...

**Comment by StHeck** [comment]
I found that if I change if [ 1 -eq 1  ] to  if [ 1 -eq 0 ] , I can get it to run. I'm not sure what  "-scalefactor=2" does.

$ cat ./start_my_roon_instance.sh
#!/bin/bash

SET_SCALEFACTOR=1

PREFIX=/home/steve/my_roon_instance
**if [ 1 -eq 0 ] <---------------------------------------------- This is [ 1 -eq 1 ] out of the box**
then
   env WINEPREFIX=/home/steve/my_roon_instance wine /home/steve/my_roon_instance/'drive_c/users/steve/Local Settings/Application Data/Roon/Application/Roon.exe' -scalefactor=2
else
   env WINEPREFIX=/home/steve/my_roon_instance wine /home/steve/my_roon_instance/'drive_c/users/steve/Local Settings/Application Data/Roon/Application/Roon.exe'
fi

**Comment by mzecher** [comment]
> I found that if I change if [ 1 -eq 1 ] to if [ 1 -eq 0 ] , I can get it to run.

Thanks that worked

**Comment by mpgarate** [comment]
That worked for me as well. Here's a one liner to patch it.

```
sed -i -e 's/-scalefactor=2/-scalefactor=1/g' $HOME/start_my_roon_instance.sh
```

**Comment by joho500** [comment]
I think something goes wrong in the script `install.sh` when creating the startup script `start_my_roon_instance.sh`. 

In line 115 of `install.sh`: 
`if [ $SET_SCALEFACTOR -eq 1 ]` gets replaced by `if [ 1 -eq 1 ]` in the resulting script file. Perhaps because SET_SCALEFACTOR is also used as a variable in the install script and is therefore replaced in this text line?

**Comment by tokr1** [comment]
> That worked for me as well. Here's a one liner to patch it.
> 
> ```
> sed -i -e 's/-scalefactor=2/-scalefactor=1/g' $HOME/start_my_roon_instance.sh
> ```

Working perfect! Thx.
