### ISSUE TITLE
Please make this run on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by jstes** [RoPieee/roon-on-wine#18]
I guess the major target audience of this effort should be end-users, in order to help switch from MS Windows to Linux (and Ubuntu is often potitioned as the best distribution for that). Well, let me tell you: it is not.

For starters, you do not even explain "clone or download". It is not realistic to assume that sort of knowledge from an end user (be it Windows of Linux).

Once you get past that, and run the ./install, the screens starts spewing error messages. I know you claim this to be a Wine problem (and you are probably right), but still, have you ever consideren for a second what that does to and end-user? It gets me totally lost. All that end-user needs is a sign that the program is proceding, and some indication of what step is being taken. All other messages need to be surpressed.

It seems that you effort is much appreciated by some. I guess those are collegue-programmers saluting you on your technical knowledge. I am an end-user scolding you for putting a - in my view, at this moment in time - totally useless piece of junk out there. No wonder Linux is getting no-where as a player in the end-user market. This is directed to the Wine developpers even more the to you well-ment but totally ill-guided effort to help.

What triggered this? You script has stopped! It is stationary since 30 minutes (see attached screen info). Now how do I clean up the mess your failure left on my computer? How do I proceed? I feel disgusted!

![Screenshot from 2021-07-06 09-37-04](https://user-images.githubusercontent.com/87003443/124561240-f6356d80-de3d-11eb-9997-d3af3c0d1b71.png)
![Screenshot from 2021-07-06 09-38-19](https://user-images.githubusercontent.com/87003443/124561245-f6ce0400-de3d-11eb-8a0b-f9f41496675b.png)

**Comment by spockfish** [comment]
So *really* don't understand open source do you? I've created something for private use (and in spare time) and put it on github. That's it. And now you come whining over here if things won't work on your end? And you expect me to help you out after this rant above?

Really?
