### ISSUE TITLE
Can't get working on Fedora w/ toolbox

### ISSUE THREAD

**Issue by Ramblurr** [RoPieee/roon-on-wine#19]
On Fedora 33 and 34  only wine 6.0 (from winehq repors) , 6.13 and 6.16  (from fedora repos) are available, but I can't get the script to work  on either of these versions.  But I am using Silverblue, so I am using fedora containers.

Should it work with these newer wine versions? Could it be a toolbox/podman issue?

**Comment by Ramblurr** [comment]
Ok fixed it. Had to change a few things:

One of the window packages URL is a 404 now, I found a new direct download URL:

```patch
-wget 'https://download.microsoft.com/download/6/E/4/6E48E8AB-DC00-419E-9704-06DD46E5F81D/NDP472-KB4054530-x86-x64-AllOS-ENU.exe'
+wget 'https://download.visualstudio.microsoft.com/download/pr/1f5af042-d0e4-4002-9c59-9ba66bcf15f6/089f837de42708daacaae7c04b7494db/ndp472-kb4054530-x86-x64-allos-enu.exe' -O ./NDP472-KB4054530-x86-x64-AllOS-ENU.exe
```

And the path to `Roon.exe` in the wine install dir has changed:

```patch
@@ -115,11 +115,12 @@ cat << _EOF_ > ./start_my_roon_instance.sh
 SET_SCALEFACTOR=$SET_SCALEFACTOR
 
 PREFIX=$PREFIX
+EXE="$PREFIX/drive_c/users/$USER/AppData/Local/Roon/Application/Roon.exe"
 if [ $SET_SCALEFACTOR -eq 1 ]
 then
-   env WINEPREFIX=$PREFIX wine $PREFIX/'drive_c/users/$USER/Local Settings/Application Data/Roon/Application/Roon.exe' -scalefactor=2
+   env WINEPREFIX=$PREFIX wine "$EXE" -scalefactor=2
 else
-   env WINEPREFIX=$PREFIX wine $PREFIX/'drive_c/users/$USER/Local Settings/Application Data/Roon/Application/Roon.exe'
+   env WINEPREFIX=$PREFIX wine "$EXE"
```

With these changes I at least can start the Roon application, haven't tried using it yet.

**Comment by Ramblurr** [comment]
Alright I can confirm with the patches above, running Roon on wine on fedora 34 works, where works entails:

* Roon app boots and is generally usable
* But I cannot play local audio on my Fedora machine (remote playing works fine)

**Comment by Yethal** [comment]
@Ramblurr Install roonbridge on your machine for local playback

**Comment by Ramblurr** [comment]
Perfect, thanks @Yethal
