### ISSUE TITLE
Fedora 36 + wine-7.12 (staging)

### ISSUE THREAD

**Issue by orsib78** [RoPieee/roon-on-wine#23]
Hello.

Recently updated my system (via DNF) including wine which resulted that Roon is unable to launch. It was worked before this update, so most probably the recent wine update to 7.12 broke someting... I also tried to wipe wine and start the installation over... Same result... However it is working again when I downgraded wine back to wine-7.2 (Staging).

The following error message appeared:

![image](https://user-images.githubusercontent.com/20341829/178993648-62c2cef9-012c-44b1-bea8-03a0b9f184af.png)

Please advise,
Balazs

**Comment by joni999** [comment]
Hi there!
I've got the exact same problem as you. I'm also on Fedora 36 and have updated to wine 7.12
Maybe we can figure out which change in the wine update causes this error.

I found the file mentioned in the error in the following path (I'm still on Wine 7.12):
(I used the following "find" command inside the install directory:)
```
#wine64-roon>  find . -iname "roon_dxgi*"
./drive_c/users/joni/AppData/Local/Roon/Application/100800988/roon_dxgi.dll 
```
Are you still on wine-7.2? Can you please check if the file is in the same location as mine?
Maybe the location where wine expects the dll has changed?

Regards
Joni

**Comment by joni999** [comment]
Hey man,

This Wine-update Fixed it for me:
https://bodhi.fedoraproject.org/updates/FEDORA-2022-f8f4823fb4

`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-f8f4823fb4`

You can probably just wait a week until it's stable or install the update manually right now.

Regards
Joni

**Comment by orsib78** [comment]
> 

Thanks. I’ll wait until the fix is officially released and then test it.

**Comment by orsib78** [comment]
I can confirm that 7.12-2 resolved the above issue.
