### ISSUE TITLE
Can't install Roon 2.0

### ISSUE THREAD

**Issue by mzecher** [RoPieee/roon-on-wine#26]
Says "this device is not compatible with Roon 2.0"
I don't know how to get details

**Comment by orsib78** [comment]
Same thing for me :(

**Comment by tokr1** [comment]
Changed win7 to win10 in the install.sh because Roon2.0 wants Windows 10 or 11 :

# setting some environment stuff
_winetricks "Setting Windows version to 10" -q win10
_winetricks "Setting DDR to OpenGL"        -q ddr=opengl
_winetricks "Disabling crash dialog"       -q nocrashdialog

The installation then continous, but fails to download 'Microsoft .NET Framework Version 4.5' .
I am not sure where/how i can set that?

**Comment by kotonbu** [comment]
> Changed win7 to win10 in the install.sh because Roon2.0 wants Windows 10 or 11 :
> 
> _winetricks "Setting Windows version to 10" -q win10
> 
> The installation then continous, but fails to download 'Microsoft .NET Framework Version 4.5' . I am not sure where/how i can set that? Why does it even need it, because a newer Version is already installed....

In the install.sh, comment out `_winetricks "Installing .NET 4.0"    -q --force dotnet40` and uncomment `_winetricks "Installing .NET 4.5.2"  -q --force dotnet452`

**Comment by tokr1** [comment]
> In the install.sh, comment out `_winetricks "Installing .NET 4.0" -q --force dotnet40` and uncomment `_winetricks "Installing .NET 4.5.2" -q --force dotnet452`

That worked. Thanks!
Just the Scalefactor doesn't work anymore, but thats probably a different story. This way I won't need my glasses anymore to use Roon :-)

**Comment by orsib78** [comment]
> > Changed win7 to win10 in the install.sh because Roon2.0 wants Windows 10 or 11 :
> > _winetricks "Setting Windows version to 10" -q win10
> > The installation then continous, but fails to download 'Microsoft .NET Framework Version 4.5' . I am not sure where/how i can set that? Why does it even need it, because a newer Version is already installed....
> 
> In the install.sh, comment out `_winetricks "Installing .NET 4.0" -q --force dotnet40` and uncomment `_winetricks "Installing .NET 4.5.2" -q --force dotnet452`

Thanks. It worked for me as well. It would worth to modify the "install.sh" accordingly.

**Comment by kotonbu** [comment]
The install script will overwrite any old start_my_roon_instance.sh with the default which has scalefactor set to 2, so that is normal.

**Comment by entity23** [comment]
Hi all,

many thanks for the update ;-)

I was a little bit sad and surprised to see my Wine installation being broken yesterday evening (after always updating smoothly before). Was about to ask for an update when I found your comments and really glad/happy to have it running on my desktop again (and surprised to find a working solution just one day after the software release).

Small side note (not causing any issues though) .. on my system, the script also downloaded/installed dot net 4.7.2 at a later point .. so maybe 4.5 might not be required (but haven't tried yet - never touch a running system)

Regarding scalefactor .. needed to change to 1 too (even on a big screen too)

**Comment by JohnFlowerful** [comment]
> so maybe 4.5 might not be required (but haven't tried yet - never touch a running system)

Using winetricks to install dotnet472 is enough since it will install 4.0 through to 4.7.2 (see [This package also includes](https://appdb.winehq.org/objectManager.php?sClass=version&iId=36188)).  
This is quite slow though... Using winetricks to install dotnet45 and then the required 4.7.2 manually is quicker.

dotnet48 works as well but it caused glitches with the window manager for me.

**Comment by benjaminbellamy** [comment]
Weird… I cannot get it to work: `roon.exe` path in `start_my_roon_instance.sh` does not exist.
Then I get this error: `00c0:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed`

**Comment by niels-anders** [comment]
thanks for all comments. In the end I got it to work with a combination of all of the above on ubuntu 22.04 + plus upgrading wine
- first install wine 7 (wine 6 that is default on 22.04  didn't work and wine 5 does not seem to be available for 22.04 or at least I could not find it) via the wine-staging branch: https://wiki.winehq.org/Ubuntu (stable branch is not available on 22.04).
- use .NET 4.5.2 as per https://github.com/RoPieee/roon-on-wine/issues/26#issuecomment-1253212178
- use win10 settings as per https://github.com/RoPieee/roon-on-wine/issues/26#issuecomment-1252892659

run the ./install.sh. This installed Roon 1.7, and through in-app updates to 1.8 and then to 2.0 it now works.

**Comment by entity23** [comment]
> Weird… I cannot get it to work: `roon.exe` path in `start_my_roon_instance.sh` does not exist. Then I get this error: `00c0:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed`

Assuming that Mono/netnet runtime is installed (as otherwise you would have ended up with an installation error) .. did you move any of the created files/folders? I prefer keeping things outside my user's directory, but adjusting paths just work fine for me)?
And .. as mentioned in another comment .. Wine 7 installed?

**Comment by benjaminbellamy** [comment]
`wine-6.0.3 (Ubuntu 6.0.3~repack-1)` 🤦‍♂️

**Comment by benjaminbellamy** [comment]
I have Roon 2.0 successfully running on Ubuntu 22.04:
- Remove Roon-on-Wine
- Type `wine --version` in a terminal. If you have version 6 or lower, you need to upgrade to version 7:
  - `sudo apt purge wine`
  - `sudo apt update`
  - `sudo apt install --install-recommends winehq-staging` (Wine has no 7 stable for Ubuntu 22.04 yet, next 7 minor release will)
  - Check that you have version 7: `$ wine --version`, you should get something like `wine-7.17 (Staging)`
- Clone roon-on-wine if you haven't: `git clone https://github.com/RoPieee/roon-on-wine.git`
- Edit `roon-on-wine/install.sh`:
  - line 82 comment `#_winetricks "Installing .NET 4.0"    -q --force dotnet40` and uncomment `_winetricks "Installing .NET 4.5.2"  -q --force dotnet452`
  - line 90 replace `_winetricks "Setting Windows version to 7" -q win7` with `_winetricks "Setting Windows version to 10" -q win10`
- run `./install.sh`
- Et voilà!
![Screenshot from 2022-09-23 11-10-05](https://user-images.githubusercontent.com/1984208/191930722-40f68c81-42ec-4690-8f97-596c2fb87cf6.png)

**Comment by joltman80** [comment]
I'm attempting this install on Arch Linux with Wine version 7.19.  I'm receiving this error:

```
0394:err:sync:RtlpWaitForCriticalSection section 00630074 "../wine/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0394, blocked by 022c, retrying (60 sec)
03a4:err:sync:RtlpWaitForCriticalSection section 00630074 "../wine/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 03a4, blocked by 022c, retrying (60 sec)

```

Not sure what I'm doing wrong.  Didn't know if this was related to the Roon install or a Wine issue.  I've made the changes listed above to the install.sh file.

**Comment by entity23** [comment]
> I'm attempting this install on Arch Linux with Wine version 7.19. I'm receiving this error:
> 
> ```
> 0394:err:sync:RtlpWaitForCriticalSection section 00630074 "../wine/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0394, blocked by 022c, retrying (60 sec)
> 03a4:err:sync:RtlpWaitForCriticalSection section 00630074 "../wine/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 03a4, blocked by 022c, retrying (60 sec)
> ```
> 
> Not sure what I'm doing wrong. Didn't know if this was related to the Roon install or a Wine issue. I've made the changes listed above to the install.sh file.

Any idea at which stage of the installation process this happened? During installation of prerequisites or did Roon installation fail?

**Comment by joltman80** [comment]
So I stepped away from the laptop for several hours.  During that time Roon finally installed.  I'm running Roon 2.0 build 1143 now.  I guess I just had to be really patient.
