### ISSUE TITLE
Upgrade to Roon 1.7 fails with Could not load type of field 'Sooloos.Application+'

### ISSUE THREAD

**Issue by niels-anders** [RoPieee/roon-on-wine#6]
First, thank you for this installer script. It helped me in the past running Roon 1.6 successfully on Ubuntu 18.04. 

Recently I upgraded my Roon Core to 1.7 and I had to upgrade the player as well. First I tried upgrading from the player itself. I expected it to fail and after the installation went fine the player didn't start up. Without further digging I removed the my_roon_instance and .wine folders to create a clean install.

I pulled the master branch to get the latest commits and after running ./install.sh the installation successfully finished. However, running roon fails with:

```
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'Sooloos.Application+<>c__DisplayClass3_0:prop_selectedlang' (1) due to: Could not load file or assembly 'RoonBase, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:RoonBase, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none>
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'Sooloos.Application+<>c__DisplayClass3_0:prop_selectedlang' (1) due to: Could not load file or assembly 'RoonBase, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:RoonBase, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none>
```

`wine --version` returns: `wine-4.0.2`

I am rather clueless. Any thoughts?

**Comment by axxelk** [comment]
not sure but after upgrading winetricks to the latest version (https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks) made it work for me. See also https://github.com/florib779/Roon/issues/1

**Comment by niels-anders** [comment]
awesome, that worked. thanks a lot :-)
