### ISSUE TITLE
Installs on Debian Buster but can't play locally

### ISSUE THREAD

**Issue by Syleron** [RoPieee/roon-on-wine#8]
Installs and runs on Debian Buster, however, cannot play audio locally. 

Any ideas?

**Comment by BastienM** [comment]
Same here.
Installed on Archlinux, when trying to play a track locally via a WASAPI device.

The tracks does load but Roon just skip them.

**Comment by Syleron** [comment]
@BastienM I ended up installing the Roon bridge on my linux box and playing via that rather than the wine player.

**Comment by BastienM** [comment]
I give up for now.
I successfully connected my core instance at home via VPN, but configuring the bridge to do so as well ... Too cumbersome for me.

**Comment by spockfish** [comment]
This is basic Roon functionality and as such has nothing to do with running Roon via Wine. You can always install a Linux Roon Bridge 'on the side'.

**Comment by jamiecurran** [comment]
I just came across this issue on Arch. I dropped all the rules on my firewall (iptables) and local audio devices appeared.
