### ISSUE TITLE
search makes roon laggish and inusable

### ISSUE THREAD

**Issue by apollotonkosmo** [RoPieee/roon-on-wine#9]
Hello first of all thanks for both ropieee and roon on wine.
Roon on wine runs perfect overall except from when I try to use search.After trying to write in to search, app is unusable and slow. This can be fixed bu closing the app and reopening it again.

Any clues?
Fedora 32
wine 5.9 staging
Roon 1.7 build 571

**Comment by fiddlesticks** [comment]
I found this - also with Fedora 32. Hadn't seen it in previous distros. 
Switching to plasma/ KDE fixed it. HTH.

**Comment by apollotonkosmo** [comment]
@fiddlesticks Thanks for sharing! I will try maybe with another wine version.

P.S. "LOL Fiddlesticks best champion ever :P"

**Comment by spockfish** [comment]
Wine still remains a 'best attempt effort'. So any problems with the Roon app itself is not something I can fix.
